# Generated by Django 2.2.6 on 2019-11-16 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=255, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'contacts',
                'verbose_name_plural': 'contacts',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('type', models.CharField(max_length=64, verbose_name='Event Type')),
                ('event_date', models.DateField(verbose_name='Events Date')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'event',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventAttendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
                ('is_responded', models.BooleanField(default=False, verbose_name='Is Responded')),
                ('is_attending', models.BooleanField(default=False, verbose_name='Is Attending')),
                ('num_of_guests', models.IntegerField(default=0, verbose_name='Number of guests attending')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_verifier_app.Contacts')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_verifier_app.Event')),
            ],
            options={
                'verbose_name': 'event_attendances',
                'verbose_name_plural': 'event_attendances',
                'db_table': 'event_attendances',
                'unique_together': {('event', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='BroadcastList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of List')),
                ('event_message_content', models.TextField(verbose_name='Message of Event')),
                ('attendances', models.ManyToManyField(to='sms_verifier_app.EventAttendances')),
                ('for_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_verifier_app.Event')),
            ],
            options={
                'verbose_name': 'broadcast_list',
                'verbose_name_plural': 'broadcast_list',
                'db_table': 'broadcast_list',
                'unique_together': {('name', 'for_event')},
            },
        ),
    ]
