# Generated by Django 2.2.6 on 2019-11-21 17:45

from django.db import migrations, models
import sms_verifier_app.models
import sms_verifier_app.storage


class Migration(migrations.Migration):

    dependencies = [
        ('sms_verifier_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='general_documents', max_length=255, storage=sms_verifier_app.storage.OverwriteStorage(), upload_to=sms_verifier_app.models.user_media_directory_path),
        ),
    ]
